spring.application.name=spring-security

# Not recommended
#spring.security.user.name=admin
#spring.security.user.password=love123

spring.datasource.url=jdbc:postgresql://localhost:5432/security_app
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
